const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');
const main=['index.html','verein.html','unternehmen.html','sponsoren.html','club-sponsors.html','kinder-familien.html','stadion.html'];
function read(file){return fs.readFileSync(path.join(root,file),'utf8')}
function markupOnly(html){return html.replace(/<script\b[\s\S]*?<\/script>/gi,'')}
function localTarget(file,href){const clean=href.split('#')[0].split('?')[0];if(!clean||clean.startsWith('#')||/^(https?:|mailto:|tel:|javascript:)/i.test(clean))return null;let target=clean.startsWith('/')?clean.slice(1):path.normalize(path.join(path.dirname(file),clean));if(target.endsWith('/'))target+='index.html';if(!path.extname(target))target+='.html';return target.replace(/\\/g,'/')}
test('main visitor pages have basic document and accessibility landmarks',()=>{for(const file of main){const html=markupOnly(read(file));assert.match(html,/<title>[^<]+<\/title>/i,`${file} title`);assert.match(html,/<meta[^>]+name=["']viewport["']/i,`${file} viewport`);assert.match(html,/<h1\b/i,`${file} h1`);for(const tag of html.match(/<img\b[^>]*>/gi)||[])assert.match(tag,/\balt=["'][^"']*["']/i,`${file} image missing alt: ${tag}`)}});
test('main-page local HTML navigation targets exist',()=>{for(const file of main){const html=markupOnly(read(file));for(const m of html.matchAll(/href=["']([^"']+)["']/gi)){const target=localTarget(file,m[1]);if(!target||target.startsWith('api/'))continue;assert.ok(fs.existsSync(path.join(root,target)),`${file} links to missing ${target}`)}}});
test('new-tab links include noopener',()=>{for(const file of fs.readdirSync(root).filter(x=>x.endsWith('.html'))){const html=markupOnly(read(file));for(const tag of html.match(/<a\b[^>]*target=["']_blank["'][^>]*>/gi)||[])assert.match(tag,/rel=["'][^"']*noopener/i,`${file} target=_blank missing noopener`)}});
test('payment, guardian, admin and legal surfaces remain non-indexed at source',()=>{for(const file of ['sponsor/checkout.html','family-plus.html','guardian/confirm.html','guardian/media-consent.html','admin/index.html','admin/readiness.html','impressum.html','datenschutz.html'])assert.match(read(file),/name=["']robots["'][^>]+noindex/i,`${file} must be noindex`)});
